"""Migrate local data contracts from the original Italian schema to English.

The project started as a personal Italian-language application. Its generated
JSON files therefore used Italian field names. This module upgrades those small
metadata files in place while leaving LanceDB and embedding vectors untouched.
No network request is made and the migration has no API cost.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from tempfile import NamedTemporaryFile


PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
GRAPH_FILE = DATA_DIR / "graph.json"
CLUSTERS_FILE = DATA_DIR / "clusters.json"
STATE_FILE = DATA_DIR / "state.json"


def _write_json_atomically(path: Path, data: dict) -> None:
    """Replace a JSON file only after its complete new version is on disk."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False, suffix=".tmp"
    ) as temporary:
        json.dump(data, temporary, ensure_ascii=False, indent=2)
        temporary.write("\n")
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, path)


def _translate_fallback_label(label: str) -> str:
    """Translate only labels generated by the application, not research terms."""
    if label == "non classificati":
        return "unclassified"
    if label == "non classificati (troppo pochi paper)":
        return "unclassified (too few papers)"
    if label.startswith("tema "):
        return "topic " + label.removeprefix("tema ")
    return label


def _migrate_graph() -> bool:
    if not GRAPH_FILE.exists():
        return False
    data = json.loads(GRAPH_FILE.read_text(encoding="utf-8"))
    changed = False
    for node in data.get("nodes", []):
        if "weak_assignment" not in node and "debole" in node:
            node["weak_assignment"] = bool(node.pop("debole"))
            changed = True
        if "cluster_label" in node:
            translated = _translate_fallback_label(node["cluster_label"])
            if translated != node["cluster_label"]:
                node["cluster_label"] = translated
                changed = True
    if changed:
        _write_json_atomically(GRAPH_FILE, data)
    return changed


def _migrate_clusters() -> bool:
    if not CLUSTERS_FILE.exists():
        return False
    data = json.loads(CLUSTERS_FILE.read_text(encoding="utf-8"))
    changed = False

    if "topics" not in data and "temi" in data:
        data["topics"] = data.pop("temi")
        changed = True
    if "assignments" not in data and "assegnazioni" in data:
        data["assignments"] = data.pop("assegnazioni")
        changed = True

    for topic in data.get("topics", []):
        renames = {
            "etichetta": "label",
            "parole_chiave": "keywords",
            "numero_paper": "paper_count",
        }
        for old, new in renames.items():
            if new not in topic and old in topic:
                topic[new] = topic.pop(old)
                changed = True
        if "label" in topic:
            translated = _translate_fallback_label(topic["label"])
            if translated != topic["label"]:
                topic["label"] = translated
                changed = True

    if changed:
        _write_json_atomically(CLUSTERS_FILE, data)
    return changed


def _migrate_state() -> bool:
    if not STATE_FILE.exists():
        return False
    data = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    if "last_zotero_version" in data or "ultima_versione" not in data:
        return False
    data["last_zotero_version"] = data.pop("ultima_versione")
    _write_json_atomically(STATE_FILE, data)
    return True


def migrate_local_data(verbose: bool = False) -> list[str]:
    """Upgrade legacy files and return the names of files that changed.

    The operation is idempotent: running it repeatedly after the first upgrade
    does nothing. This makes it safe to call at every application start.
    """
    migrated: list[str] = []
    for path, operation in (
        (GRAPH_FILE, _migrate_graph),
        (CLUSTERS_FILE, _migrate_clusters),
        (STATE_FILE, _migrate_state),
    ):
        if operation():
            migrated.append(path.name)
    if verbose and migrated:
        print("Migrated local metadata to the English schema: " + ", ".join(migrated))
    return migrated
